### ISSUE TITLE
Not found response_top_headlinews_news.g.dart

### ISSUE THREAD

**Issue by Nimto007** [CoderJava/Flutter-News-App#1]
Not found response_top_headlinews_news.g.dart

**Comment by CoderJava** [comment]
> Not found response_top_headlinews_news.g.dart

Sorry for that. You must run command json_serializable to create that file. Run this command in project directory.
`flutter pub run build_runner build`
Or if that command failed please run this command.
`flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by CoderJava** [comment]
> Not found response_top_headlinews_news.g.dart

I have updated repository. You can pull again.
[da7a64e](https://github.com/CoderJava/Flutter-News-App/commit/da7a64e8bf7fe09bbc41bedf5d4fa2cfc234e857)
