### ISSUE TITLE
How do I test run this app?

### ISSUE THREAD

**Issue by roshangeoroy** [CoderJava/Flutter-News-App#33]
I am really new to flutter and trying to figure things out. How do I test run this app?  Normally I do it using the main.dart, but I can't find it. I'm also really interested to contribute to this project. Please guide me

**Comment by CoderJava** [comment]
You can use file main_development.dart or main_production.dart. Please read README.md. I have write documentation on it.

**Comment by roshangeoroy** [comment]
> You can use file main_development.dart or main_production.dart. Please read README.md. I have write documentation on it.

Thank you! my bad. I did read it but might have missed it out!
