### ISSUE TITLE
Master branch showing errors related mockito and other dependencies

### ISSUE THREAD

**Issue by Abhishek201999** [CoderJava/Flutter-News-App#37]
Because no versions of mockito match >4.1.1 <4.1.1+1 and mockito >=4.1.1+1 <4.1.2 depends on test_api >=0.2.1 <0.4.0

**Comment by CoderJava** [comment]
I'm working on to update this app on branch **dev-v3.0.0**. And because of that I will close this issue until branch **dev-v3.0.0** is finished.
