### ISSUE TITLE
CAN'T RUN THE APP DUE TO ENVIRONMENT & FLUTTER VERSION MISMATCH

### ISSUE THREAD

**Issue by GwamakaCharles** [CoderJava/Flutter-News-App#39]
I'm trying to run this app by following the instructions in the Readme. Both in production and development environment. Since I didn't know the flutter version for the project, `I failed miserably running it on Flutter version 2.10.5`. So I tried multiple options, going 2 years back since that's when the project was shared. So **I tried Flutter version 1.17.0, and all went well** except I run into this error **No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi**. I checked online for solutions and got this [possible solution](https://stackoverflow.com/questions/66922162/no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-arm-linux), which resulted into several other errors! This led me into believing that maybe I don't know the precise environment in which this project was successfully deployed on. Can you share the environment specifications including the flutter version for this project please?

**Comment by CoderJava** [comment]
Sorry about that. I don't remember Flutter version that I'm used in branch **master**. And now I'm working on to update this app in branch **dev-v3.0.0**. And for now I think I will close this issue until branch **dev-v3.0.0** is finished.

**Comment by GwamakaCharles** [comment]
Fair enough!
